/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sina.recomm.engine.idl;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * query engine interfaces.
 */
public class IndexingAttachment implements org.apache.thrift.TBase<IndexingAttachment, IndexingAttachment._Fields>, java.io.Serializable, Cloneable, Comparable<IndexingAttachment> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("IndexingAttachment");

  private static final org.apache.thrift.protocol.TField GLOBAL_DOCID_FIELD_DESC = new org.apache.thrift.protocol.TField("global_docid", org.apache.thrift.protocol.TType.I64, (short)1);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new IndexingAttachmentStandardSchemeFactory());
    schemes.put(TupleScheme.class, new IndexingAttachmentTupleSchemeFactory());
  }

  public long global_docid; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    GLOBAL_DOCID((short)1, "global_docid");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // GLOBAL_DOCID
          return GLOBAL_DOCID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __GLOBAL_DOCID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.GLOBAL_DOCID, new org.apache.thrift.meta_data.FieldMetaData("global_docid", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(IndexingAttachment.class, metaDataMap);
  }

  public IndexingAttachment() {
  }

  public IndexingAttachment(
    long global_docid)
  {
    this();
    this.global_docid = global_docid;
    setGlobal_docidIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public IndexingAttachment(IndexingAttachment other) {
    __isset_bitfield = other.__isset_bitfield;
    this.global_docid = other.global_docid;
  }

  public IndexingAttachment deepCopy() {
    return new IndexingAttachment(this);
  }

  @Override
  public void clear() {
    setGlobal_docidIsSet(false);
    this.global_docid = 0;
  }

  public long getGlobal_docid() {
    return this.global_docid;
  }

  public IndexingAttachment setGlobal_docid(long global_docid) {
    this.global_docid = global_docid;
    setGlobal_docidIsSet(true);
    return this;
  }

  public void unsetGlobal_docid() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __GLOBAL_DOCID_ISSET_ID);
  }

  /** Returns true if field global_docid is set (has been assigned a value) and false otherwise */
  public boolean isSetGlobal_docid() {
    return EncodingUtils.testBit(__isset_bitfield, __GLOBAL_DOCID_ISSET_ID);
  }

  public void setGlobal_docidIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __GLOBAL_DOCID_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case GLOBAL_DOCID:
      if (value == null) {
        unsetGlobal_docid();
      } else {
        setGlobal_docid((Long)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case GLOBAL_DOCID:
      return Long.valueOf(getGlobal_docid());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case GLOBAL_DOCID:
      return isSetGlobal_docid();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof IndexingAttachment)
      return this.equals((IndexingAttachment)that);
    return false;
  }

  public boolean equals(IndexingAttachment that) {
    if (that == null)
      return false;

    boolean this_present_global_docid = true;
    boolean that_present_global_docid = true;
    if (this_present_global_docid || that_present_global_docid) {
      if (!(this_present_global_docid && that_present_global_docid))
        return false;
      if (this.global_docid != that.global_docid)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(IndexingAttachment other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetGlobal_docid()).compareTo(other.isSetGlobal_docid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGlobal_docid()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.global_docid, other.global_docid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("IndexingAttachment(");
    boolean first = true;

    sb.append("global_docid:");
    sb.append(this.global_docid);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'global_docid' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class IndexingAttachmentStandardSchemeFactory implements SchemeFactory {
    public IndexingAttachmentStandardScheme getScheme() {
      return new IndexingAttachmentStandardScheme();
    }
  }

  private static class IndexingAttachmentStandardScheme extends StandardScheme<IndexingAttachment> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, IndexingAttachment struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // GLOBAL_DOCID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.global_docid = iprot.readI64();
              struct.setGlobal_docidIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetGlobal_docid()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'global_docid' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, IndexingAttachment struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(GLOBAL_DOCID_FIELD_DESC);
      oprot.writeI64(struct.global_docid);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class IndexingAttachmentTupleSchemeFactory implements SchemeFactory {
    public IndexingAttachmentTupleScheme getScheme() {
      return new IndexingAttachmentTupleScheme();
    }
  }

  private static class IndexingAttachmentTupleScheme extends TupleScheme<IndexingAttachment> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, IndexingAttachment struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI64(struct.global_docid);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, IndexingAttachment struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.global_docid = iprot.readI64();
      struct.setGlobal_docidIsSet(true);
    }
  }

}

