/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sina.recomm.engine.idl;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RecommendationResponse implements org.apache.thrift.TBase<RecommendationResponse, RecommendationResponse._Fields>, java.io.Serializable, Cloneable, Comparable<RecommendationResponse> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RecommendationResponse");

  private static final org.apache.thrift.protocol.TField RESPONSE_CODE_FIELD_DESC = new org.apache.thrift.protocol.TField("response_code", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField RESULTS_FIELD_DESC = new org.apache.thrift.protocol.TField("results", org.apache.thrift.protocol.TType.LIST, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RecommendationResponseStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RecommendationResponseTupleSchemeFactory());
  }

  /**
   * 
   * @see RecommendationResponseCode
   */
  public RecommendationResponseCode response_code; // required
  public List<RecommendationResult> results; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    /**
     * 
     * @see RecommendationResponseCode
     */
    RESPONSE_CODE((short)1, "response_code"),
    RESULTS((short)2, "results");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // RESPONSE_CODE
          return RESPONSE_CODE;
        case 2: // RESULTS
          return RESULTS;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.RESPONSE_CODE, new org.apache.thrift.meta_data.FieldMetaData("response_code", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.EnumMetaData(org.apache.thrift.protocol.TType.ENUM, RecommendationResponseCode.class)));
    tmpMap.put(_Fields.RESULTS, new org.apache.thrift.meta_data.FieldMetaData("results", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, RecommendationResult.class))));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RecommendationResponse.class, metaDataMap);
  }

  public RecommendationResponse() {
    this.response_code = com.sina.recomm.engine.idl.RecommendationResponseCode.RRC_OK;

  }

  public RecommendationResponse(
    RecommendationResponseCode response_code,
    List<RecommendationResult> results)
  {
    this();
    this.response_code = response_code;
    this.results = results;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RecommendationResponse(RecommendationResponse other) {
    if (other.isSetResponse_code()) {
      this.response_code = other.response_code;
    }
    if (other.isSetResults()) {
      List<RecommendationResult> __this__results = new ArrayList<RecommendationResult>(other.results.size());
      for (RecommendationResult other_element : other.results) {
        __this__results.add(new RecommendationResult(other_element));
      }
      this.results = __this__results;
    }
  }

  public RecommendationResponse deepCopy() {
    return new RecommendationResponse(this);
  }

  @Override
  public void clear() {
    this.response_code = com.sina.recomm.engine.idl.RecommendationResponseCode.RRC_OK;

    this.results = null;
  }

  /**
   * 
   * @see RecommendationResponseCode
   */
  public RecommendationResponseCode getResponse_code() {
    return this.response_code;
  }

  /**
   * 
   * @see RecommendationResponseCode
   */
  public RecommendationResponse setResponse_code(RecommendationResponseCode response_code) {
    this.response_code = response_code;
    return this;
  }

  public void unsetResponse_code() {
    this.response_code = null;
  }

  /** Returns true if field response_code is set (has been assigned a value) and false otherwise */
  public boolean isSetResponse_code() {
    return this.response_code != null;
  }

  public void setResponse_codeIsSet(boolean value) {
    if (!value) {
      this.response_code = null;
    }
  }

  public int getResultsSize() {
    return (this.results == null) ? 0 : this.results.size();
  }

  public java.util.Iterator<RecommendationResult> getResultsIterator() {
    return (this.results == null) ? null : this.results.iterator();
  }

  public void addToResults(RecommendationResult elem) {
    if (this.results == null) {
      this.results = new ArrayList<RecommendationResult>();
    }
    this.results.add(elem);
  }

  public List<RecommendationResult> getResults() {
    return this.results;
  }

  public RecommendationResponse setResults(List<RecommendationResult> results) {
    this.results = results;
    return this;
  }

  public void unsetResults() {
    this.results = null;
  }

  /** Returns true if field results is set (has been assigned a value) and false otherwise */
  public boolean isSetResults() {
    return this.results != null;
  }

  public void setResultsIsSet(boolean value) {
    if (!value) {
      this.results = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case RESPONSE_CODE:
      if (value == null) {
        unsetResponse_code();
      } else {
        setResponse_code((RecommendationResponseCode)value);
      }
      break;

    case RESULTS:
      if (value == null) {
        unsetResults();
      } else {
        setResults((List<RecommendationResult>)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case RESPONSE_CODE:
      return getResponse_code();

    case RESULTS:
      return getResults();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case RESPONSE_CODE:
      return isSetResponse_code();
    case RESULTS:
      return isSetResults();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RecommendationResponse)
      return this.equals((RecommendationResponse)that);
    return false;
  }

  public boolean equals(RecommendationResponse that) {
    if (that == null)
      return false;

    boolean this_present_response_code = true && this.isSetResponse_code();
    boolean that_present_response_code = true && that.isSetResponse_code();
    if (this_present_response_code || that_present_response_code) {
      if (!(this_present_response_code && that_present_response_code))
        return false;
      if (!this.response_code.equals(that.response_code))
        return false;
    }

    boolean this_present_results = true && this.isSetResults();
    boolean that_present_results = true && that.isSetResults();
    if (this_present_results || that_present_results) {
      if (!(this_present_results && that_present_results))
        return false;
      if (!this.results.equals(that.results))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(RecommendationResponse other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetResponse_code()).compareTo(other.isSetResponse_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResponse_code()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.response_code, other.response_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetResults()).compareTo(other.isSetResults());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetResults()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.results, other.results);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RecommendationResponse(");
    boolean first = true;

    sb.append("response_code:");
    if (this.response_code == null) {
      sb.append("null");
    } else {
      sb.append(this.response_code);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("results:");
    if (this.results == null) {
      sb.append("null");
    } else {
      sb.append(this.results);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (response_code == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'response_code' was not present! Struct: " + toString());
    }
    if (results == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'results' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RecommendationResponseStandardSchemeFactory implements SchemeFactory {
    public RecommendationResponseStandardScheme getScheme() {
      return new RecommendationResponseStandardScheme();
    }
  }

  private static class RecommendationResponseStandardScheme extends StandardScheme<RecommendationResponse> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RecommendationResponse struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // RESPONSE_CODE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.response_code = RecommendationResponseCode.findByValue(iprot.readI32());
              struct.setResponse_codeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // RESULTS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list0 = iprot.readListBegin();
                struct.results = new ArrayList<RecommendationResult>(_list0.size);
                for (int _i1 = 0; _i1 < _list0.size; ++_i1)
                {
                  RecommendationResult _elem2;
                  _elem2 = new RecommendationResult();
                  _elem2.read(iprot);
                  struct.results.add(_elem2);
                }
                iprot.readListEnd();
              }
              struct.setResultsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RecommendationResponse struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.response_code != null) {
        oprot.writeFieldBegin(RESPONSE_CODE_FIELD_DESC);
        oprot.writeI32(struct.response_code.getValue());
        oprot.writeFieldEnd();
      }
      if (struct.results != null) {
        oprot.writeFieldBegin(RESULTS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.results.size()));
          for (RecommendationResult _iter3 : struct.results)
          {
            _iter3.write(oprot);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RecommendationResponseTupleSchemeFactory implements SchemeFactory {
    public RecommendationResponseTupleScheme getScheme() {
      return new RecommendationResponseTupleScheme();
    }
  }

  private static class RecommendationResponseTupleScheme extends TupleScheme<RecommendationResponse> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RecommendationResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeI32(struct.response_code.getValue());
      {
        oprot.writeI32(struct.results.size());
        for (RecommendationResult _iter4 : struct.results)
        {
          _iter4.write(oprot);
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RecommendationResponse struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.response_code = RecommendationResponseCode.findByValue(iprot.readI32());
      struct.setResponse_codeIsSet(true);
      {
        org.apache.thrift.protocol.TList _list5 = new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, iprot.readI32());
        struct.results = new ArrayList<RecommendationResult>(_list5.size);
        for (int _i6 = 0; _i6 < _list5.size; ++_i6)
        {
          RecommendationResult _elem7;
          _elem7 = new RecommendationResult();
          _elem7.read(iprot);
          struct.results.add(_elem7);
        }
      }
      struct.setResultsIsSet(true);
    }
  }

}

