/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sina.recomm.engine.idl;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class RecommendationResult implements org.apache.thrift.TBase<RecommendationResult, RecommendationResult._Fields>, java.io.Serializable, Cloneable, Comparable<RecommendationResult> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("RecommendationResult");

  private static final org.apache.thrift.protocol.TField STORY_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("story_id", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SCORE_FIELD_DESC = new org.apache.thrift.protocol.TField("score", org.apache.thrift.protocol.TType.DOUBLE, (short)2);
  private static final org.apache.thrift.protocol.TField DEBUG_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("debug_info", org.apache.thrift.protocol.TType.STRING, (short)3);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new RecommendationResultStandardSchemeFactory());
    schemes.put(TupleScheme.class, new RecommendationResultTupleSchemeFactory());
  }

  public String story_id; // required
  public double score; // required
  public String debug_info; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    STORY_ID((short)1, "story_id"),
    SCORE((short)2, "score"),
    DEBUG_INFO((short)3, "debug_info");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // STORY_ID
          return STORY_ID;
        case 2: // SCORE
          return SCORE;
        case 3: // DEBUG_INFO
          return DEBUG_INFO;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SCORE_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.DEBUG_INFO};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.STORY_ID, new org.apache.thrift.meta_data.FieldMetaData("story_id", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SCORE, new org.apache.thrift.meta_data.FieldMetaData("score", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.DOUBLE)));
    tmpMap.put(_Fields.DEBUG_INFO, new org.apache.thrift.meta_data.FieldMetaData("debug_info", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(RecommendationResult.class, metaDataMap);
  }

  public RecommendationResult() {
    this.score = 100;

  }

  public RecommendationResult(
    String story_id,
    double score)
  {
    this();
    this.story_id = story_id;
    this.score = score;
    setScoreIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public RecommendationResult(RecommendationResult other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetStory_id()) {
      this.story_id = other.story_id;
    }
    this.score = other.score;
    if (other.isSetDebug_info()) {
      this.debug_info = other.debug_info;
    }
  }

  public RecommendationResult deepCopy() {
    return new RecommendationResult(this);
  }

  @Override
  public void clear() {
    this.story_id = null;
    this.score = 100;

    this.debug_info = null;
  }

  public String getStory_id() {
    return this.story_id;
  }

  public RecommendationResult setStory_id(String story_id) {
    this.story_id = story_id;
    return this;
  }

  public void unsetStory_id() {
    this.story_id = null;
  }

  /** Returns true if field story_id is set (has been assigned a value) and false otherwise */
  public boolean isSetStory_id() {
    return this.story_id != null;
  }

  public void setStory_idIsSet(boolean value) {
    if (!value) {
      this.story_id = null;
    }
  }

  public double getScore() {
    return this.score;
  }

  public RecommendationResult setScore(double score) {
    this.score = score;
    setScoreIsSet(true);
    return this;
  }

  public void unsetScore() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __SCORE_ISSET_ID);
  }

  /** Returns true if field score is set (has been assigned a value) and false otherwise */
  public boolean isSetScore() {
    return EncodingUtils.testBit(__isset_bitfield, __SCORE_ISSET_ID);
  }

  public void setScoreIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __SCORE_ISSET_ID, value);
  }

  public String getDebug_info() {
    return this.debug_info;
  }

  public RecommendationResult setDebug_info(String debug_info) {
    this.debug_info = debug_info;
    return this;
  }

  public void unsetDebug_info() {
    this.debug_info = null;
  }

  /** Returns true if field debug_info is set (has been assigned a value) and false otherwise */
  public boolean isSetDebug_info() {
    return this.debug_info != null;
  }

  public void setDebug_infoIsSet(boolean value) {
    if (!value) {
      this.debug_info = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case STORY_ID:
      if (value == null) {
        unsetStory_id();
      } else {
        setStory_id((String)value);
      }
      break;

    case SCORE:
      if (value == null) {
        unsetScore();
      } else {
        setScore((Double)value);
      }
      break;

    case DEBUG_INFO:
      if (value == null) {
        unsetDebug_info();
      } else {
        setDebug_info((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case STORY_ID:
      return getStory_id();

    case SCORE:
      return Double.valueOf(getScore());

    case DEBUG_INFO:
      return getDebug_info();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case STORY_ID:
      return isSetStory_id();
    case SCORE:
      return isSetScore();
    case DEBUG_INFO:
      return isSetDebug_info();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof RecommendationResult)
      return this.equals((RecommendationResult)that);
    return false;
  }

  public boolean equals(RecommendationResult that) {
    if (that == null)
      return false;

    boolean this_present_story_id = true && this.isSetStory_id();
    boolean that_present_story_id = true && that.isSetStory_id();
    if (this_present_story_id || that_present_story_id) {
      if (!(this_present_story_id && that_present_story_id))
        return false;
      if (!this.story_id.equals(that.story_id))
        return false;
    }

    boolean this_present_score = true;
    boolean that_present_score = true;
    if (this_present_score || that_present_score) {
      if (!(this_present_score && that_present_score))
        return false;
      if (this.score != that.score)
        return false;
    }

    boolean this_present_debug_info = true && this.isSetDebug_info();
    boolean that_present_debug_info = true && that.isSetDebug_info();
    if (this_present_debug_info || that_present_debug_info) {
      if (!(this_present_debug_info && that_present_debug_info))
        return false;
      if (!this.debug_info.equals(that.debug_info))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(RecommendationResult other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetStory_id()).compareTo(other.isSetStory_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStory_id()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.story_id, other.story_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetScore()).compareTo(other.isSetScore());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetScore()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.score, other.score);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetDebug_info()).compareTo(other.isSetDebug_info());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDebug_info()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.debug_info, other.debug_info);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("RecommendationResult(");
    boolean first = true;

    sb.append("story_id:");
    if (this.story_id == null) {
      sb.append("null");
    } else {
      sb.append(this.story_id);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("score:");
    sb.append(this.score);
    first = false;
    if (isSetDebug_info()) {
      if (!first) sb.append(", ");
      sb.append("debug_info:");
      if (this.debug_info == null) {
        sb.append("null");
      } else {
        sb.append(this.debug_info);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (story_id == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'story_id' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'score' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class RecommendationResultStandardSchemeFactory implements SchemeFactory {
    public RecommendationResultStandardScheme getScheme() {
      return new RecommendationResultStandardScheme();
    }
  }

  private static class RecommendationResultStandardScheme extends StandardScheme<RecommendationResult> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, RecommendationResult struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // STORY_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.story_id = iprot.readString();
              struct.setStory_idIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SCORE
            if (schemeField.type == org.apache.thrift.protocol.TType.DOUBLE) {
              struct.score = iprot.readDouble();
              struct.setScoreIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // DEBUG_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.debug_info = iprot.readString();
              struct.setDebug_infoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetScore()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'score' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, RecommendationResult struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.story_id != null) {
        oprot.writeFieldBegin(STORY_ID_FIELD_DESC);
        oprot.writeString(struct.story_id);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(SCORE_FIELD_DESC);
      oprot.writeDouble(struct.score);
      oprot.writeFieldEnd();
      if (struct.debug_info != null) {
        if (struct.isSetDebug_info()) {
          oprot.writeFieldBegin(DEBUG_INFO_FIELD_DESC);
          oprot.writeString(struct.debug_info);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class RecommendationResultTupleSchemeFactory implements SchemeFactory {
    public RecommendationResultTupleScheme getScheme() {
      return new RecommendationResultTupleScheme();
    }
  }

  private static class RecommendationResultTupleScheme extends TupleScheme<RecommendationResult> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, RecommendationResult struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      oprot.writeString(struct.story_id);
      oprot.writeDouble(struct.score);
      BitSet optionals = new BitSet();
      if (struct.isSetDebug_info()) {
        optionals.set(0);
      }
      oprot.writeBitSet(optionals, 1);
      if (struct.isSetDebug_info()) {
        oprot.writeString(struct.debug_info);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, RecommendationResult struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      struct.story_id = iprot.readString();
      struct.setStory_idIsSet(true);
      struct.score = iprot.readDouble();
      struct.setScoreIsSet(true);
      BitSet incoming = iprot.readBitSet(1);
      if (incoming.get(0)) {
        struct.debug_info = iprot.readString();
        struct.setDebug_infoIsSet(true);
      }
    }
  }

}

