/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sina.recomm.engine.idl;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum RecommendationResponseCode implements org.apache.thrift.TEnum {
  RRC_OK(0),
  RRC_ERROR(1),
  RRC_UID_NOT_FOUND(2),
  RRC_NO_DOC(3),
  RRC_NO_CANDIDATE(4),
  RRC_NO_PROFILE(5),
  RRC_EMPTY_RANK_RESULT(6);

  private final int value;

  private RecommendationResponseCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static RecommendationResponseCode findByValue(int value) { 
    switch (value) {
      case 0:
        return RRC_OK;
      case 1:
        return RRC_ERROR;
      case 2:
        return RRC_UID_NOT_FOUND;
      case 3:
        return RRC_NO_DOC;
      case 4:
        return RRC_NO_CANDIDATE;
      case 5:
        return RRC_NO_PROFILE;
      case 6:
        return RRC_EMPTY_RANK_RESULT;
      default:
        return null;
    }
  }
}
