/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sina.recomm.engine.idl;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

/**
 * - a story is a candidate to be recommended
 */
public enum StoryManagementStatus implements org.apache.thrift.TEnum {
  SMS_OK(0),
  SMS_ERROR(1);

  private final int value;

  private StoryManagementStatus(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static StoryManagementStatus findByValue(int value) { 
    switch (value) {
      case 0:
        return SMS_OK;
      case 1:
        return SMS_ERROR;
      default:
        return null;
    }
  }
}
