/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.sina.recomm.engine.idl;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum UserEngagementType implements org.apache.thrift.TEnum {
  UET_CLICK(0),
  UET_FAVORITE(2),
  UET_SHARE(3),
  UET_LIKE(4);

  private final int value;

  private UserEngagementType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static UserEngagementType findByValue(int value) { 
    switch (value) {
      case 0:
        return UET_CLICK;
      case 2:
        return UET_FAVORITE;
      case 3:
        return UET_SHARE;
      case 4:
        return UET_LIKE;
      default:
        return null;
    }
  }
}
