/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "recomm_engine_constants.h"

namespace recomm_engine { namespace idl {

const recomm_engineConstants g_recomm_engine_constants;

recomm_engineConstants::recomm_engineConstants() {
}

}} // namespace

