/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef recomm_engine_CONSTANTS_H
#define recomm_engine_CONSTANTS_H

#include "recomm_engine_types.h"

namespace recomm_engine { namespace idl {

class recomm_engineConstants {
 public:
  recomm_engineConstants();

};

extern const recomm_engineConstants g_recomm_engine_constants;

}} // namespace

#endif
