/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef RetrievalEngine_H
#define RetrievalEngine_H

#include <thrift/TDispatchProcessor.h>
#include "recomm_engine_types.h"

namespace recomm_engine { namespace idl {

class RetrievalEngineIf {
 public:
  virtual ~RetrievalEngineIf() {}
  virtual void search(RetrievalResponse& _return, const RetrievalRequest& request) = 0;
};

class RetrievalEngineIfFactory {
 public:
  typedef RetrievalEngineIf Handler;

  virtual ~RetrievalEngineIfFactory() {}

  virtual RetrievalEngineIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(RetrievalEngineIf* /* handler */) = 0;
};

class RetrievalEngineIfSingletonFactory : virtual public RetrievalEngineIfFactory {
 public:
  RetrievalEngineIfSingletonFactory(const boost::shared_ptr<RetrievalEngineIf>& iface) : iface_(iface) {}
  virtual ~RetrievalEngineIfSingletonFactory() {}

  virtual RetrievalEngineIf* getHandler(const ::apache::thrift::TConnectionInfo&) {
    return iface_.get();
  }
  virtual void releaseHandler(RetrievalEngineIf* /* handler */) {}

 protected:
  boost::shared_ptr<RetrievalEngineIf> iface_;
};

class RetrievalEngineNull : virtual public RetrievalEngineIf {
 public:
  virtual ~RetrievalEngineNull() {}
  void search(RetrievalResponse& /* _return */, const RetrievalRequest& /* request */) {
    return;
  }
};

typedef struct _RetrievalEngine_search_args__isset {
  _RetrievalEngine_search_args__isset() : request(false) {}
  bool request;
} _RetrievalEngine_search_args__isset;

class RetrievalEngine_search_args {
 public:

  RetrievalEngine_search_args() {
  }

  virtual ~RetrievalEngine_search_args() throw() {}

  RetrievalRequest request;

  _RetrievalEngine_search_args__isset __isset;

  void __set_request(const RetrievalRequest& val) {
    request = val;
  }

  bool operator == (const RetrievalEngine_search_args & rhs) const
  {
    if (!(request == rhs.request))
      return false;
    return true;
  }
  bool operator != (const RetrievalEngine_search_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RetrievalEngine_search_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class RetrievalEngine_search_pargs {
 public:


  virtual ~RetrievalEngine_search_pargs() throw() {}

  const RetrievalRequest* request;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RetrievalEngine_search_result__isset {
  _RetrievalEngine_search_result__isset() : success(false) {}
  bool success;
} _RetrievalEngine_search_result__isset;

class RetrievalEngine_search_result {
 public:

  RetrievalEngine_search_result() {
  }

  virtual ~RetrievalEngine_search_result() throw() {}

  RetrievalResponse success;

  _RetrievalEngine_search_result__isset __isset;

  void __set_success(const RetrievalResponse& val) {
    success = val;
  }

  bool operator == (const RetrievalEngine_search_result & rhs) const
  {
    if (!(success == rhs.success))
      return false;
    return true;
  }
  bool operator != (const RetrievalEngine_search_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const RetrievalEngine_search_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _RetrievalEngine_search_presult__isset {
  _RetrievalEngine_search_presult__isset() : success(false) {}
  bool success;
} _RetrievalEngine_search_presult__isset;

class RetrievalEngine_search_presult {
 public:


  virtual ~RetrievalEngine_search_presult() throw() {}

  RetrievalResponse* success;

  _RetrievalEngine_search_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class RetrievalEngineClient : virtual public RetrievalEngineIf {
 public:
  RetrievalEngineClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) :
    piprot_(prot),
    poprot_(prot) {
    iprot_ = prot.get();
    oprot_ = prot.get();
  }
  RetrievalEngineClient(boost::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, boost::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) :
    piprot_(iprot),
    poprot_(oprot) {
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void search(RetrievalResponse& _return, const RetrievalRequest& request);
  void send_search(const RetrievalRequest& request);
  void recv_search(RetrievalResponse& _return);
 protected:
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  boost::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class RetrievalEngineProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  boost::shared_ptr<RetrievalEngineIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext);
 private:
  typedef  void (RetrievalEngineProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_search(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  RetrievalEngineProcessor(boost::shared_ptr<RetrievalEngineIf> iface) :
    iface_(iface) {
    processMap_["search"] = &RetrievalEngineProcessor::process_search;
  }

  virtual ~RetrievalEngineProcessor() {}
};

class RetrievalEngineProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  RetrievalEngineProcessorFactory(const ::boost::shared_ptr< RetrievalEngineIfFactory >& handlerFactory) :
      handlerFactory_(handlerFactory) {}

  ::boost::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo);

 protected:
  ::boost::shared_ptr< RetrievalEngineIfFactory > handlerFactory_;
};

class RetrievalEngineMultiface : virtual public RetrievalEngineIf {
 public:
  RetrievalEngineMultiface(std::vector<boost::shared_ptr<RetrievalEngineIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~RetrievalEngineMultiface() {}
 protected:
  std::vector<boost::shared_ptr<RetrievalEngineIf> > ifaces_;
  RetrievalEngineMultiface() {}
  void add(boost::shared_ptr<RetrievalEngineIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void search(RetrievalResponse& _return, const RetrievalRequest& request) {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->search(_return, request);
    }
    ifaces_[i]->search(_return, request);
    return;
  }

};

}} // namespace

#endif
