// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "StoryManagement.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::recomm_engine::idl;

class StoryManagementHandler : virtual public StoryManagementIf {
 public:
  StoryManagementHandler() {
    // Your initialization goes here
  }

  void add_story(StoryAddingResponse& _return, const StoryAddingRequest& request) {
    // Your implementation goes here
    printf("add_story\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<StoryManagementHandler> handler(new StoryManagementHandler());
  shared_ptr<TProcessor> processor(new StoryManagementProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

